# Metadata about this component, to be used in the CMS
######################
# Only appeared to be in use as a subcomponent, so have removed it from showing in CC... 
# can be made to show in CC again by adding structures: ['content_blocks'] to the spec below
######################
spec:
  structures: []
  label: Contact Form
  description: Contact Form
  icon: 'checklist_rtl'
  tags: ['Form']

# Defines the structure of this component, as well as the default values
blueprint:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
