# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Image block
  description: Large image block with optional heading
  icon: 'image'
  tags: ['Image']
  picker_preview:
    gallery:
      image: /public/component_thumbnails/image-block.preview.png

# Defines the structure of this component, as well as the default values
blueprint:
  top_spacing:
  bottom_spacing:
  pre_title:
  title: 
  image:
    src:
    alt:
    title:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
